version: '3.8'

services:
  # 1. PostgreSQL Database
  db:
    image: postgres:15
    container_name: bank_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: pfe_password
      POSTGRES_DB: bank_warehouse
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - bank_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin"]
      interval: 10s
      timeout: 5s
      retries: 5

  # 2. Flask Web Application
  web:
    build: .
    container_name: credit_risk_app
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://admin:pfe_password@db:5432/bank_warehouse
      - FLASK_APP=app.py
    volumes:
      - ./uploads:/app/uploads
      - .:/app
    networks:
      - bank_network
    command: python app.py

  # 3. Apache Airflow (Orchestrator)
  airflow:
    image: apache/airflow:2.7.1-python3.9
    container_name: airflow_orchestrator
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql://admin:pfe_password@db:5432/airflow_db
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__CORE__DAGS_FOLDER=/opt/airflow/dags
      - AIRFLOW__WEBSERVER__SECRET_KEY=nb_bank_2026
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./uploads:/opt/airflow/uploads
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - bank_network
    command: >
      bash -c "airflow db init && 
               airflow db upgrade && 
               airflow users create --username admin --password admin --firstname admin --lastname admin --role Admin --email admin@example.com || true && 
               (airflow webserver --port 8080 & airflow scheduler)"

volumes:
  postgres_data:

networks:
  bank_network:
    driver: bridge